### ISSUE TITLE
Add a .reacli config file in projects to set a project configuration

### ISSUE THREAD

**Issue by gdarchen** [tanohzana/reacli#13]
**Is your feature request related to a problem? Please describe.**
When we use _Reacli_ in a project, we might want to generate multiple components with the same arguments (`--flow`, `--scss`...).

**Describe the solution you'd like**
A solution I can imagine would be to enable creating a `.reacli` file at the root of projects using the CLI. In this file, we would describe the project's configuration for the _Reacli_ tool such as whether it uses Flow, Sass files, Redux... Then, the user could only have to ask for the creation of a new component (maybe add an option enabling not to use the `.reacli` and generate a component with no option at all ?).  

**Describe alternatives you've considered**
I can't imagine another option that rewriting each time every parameter we want to use for _Reacli_.

**Additional context**
The `.reacli` file could be pretty simple, for instance:

```json
{
    "flow": true,
    "redux": false,
    "scss": true,
}
```

**Comment by anatol-grabowski** [comment]
maybe a .reacli directory where one can put custom templates along with the config.json would be better

**Comment by tanohzana** [comment]
@grabantot CLI is to be installed as a global package. Therefore, the actual user (not dev) will have no idea how we manage our templating system, and should not be messing with templates location.

However, it could be interesting indeed to store custom template from the user, but not in a `.reacli` folder but rather in the basic `templates` folder. This is another issue 😄
