### ISSUE TITLE
Add commander to manage cmd args and help

### ISSUE THREAD

**Issue by lcor-io** [tanohzana/reacli#14]
**Is your feature request related to a problem? Please describe.**
Currently there is no documentation or help in the CLI. The user should have access to the list of available commands.

**Describe the solution you'd like**
`reacli -h`, `reacli --help` or `man reacli` should prompt all available commands. The help could also be prompted if the user write an incorrect parameter.

**Comment by gdarchen** [comment]
That sounds good to me. This help should also be sent back to the user when there is an error in the command 😉
