### ISSUE TITLE
Add a template solution

### ISSUE THREAD

**Issue by lcor-io** [tanohzana/reacli#17]
**Is your feature request related to a problem? Please describe.**
For now, we use our own template system. We should rely on another npm template library, and focus on new features.

**Describe the solution you'd 
[string template](https://www.npmjs.com/package/string-template), [string placeholder](https://www.npmjs.com/package/string-placeholder) and [mustache.js](https://github.com/janl/mustache.js) all seems plausibe solution. Feel free to add more

**Comment by tanohzana** [comment]
I'll do it tonight 😉

**Comment by tanohzana** [comment]
Number of downloads during the previous week :

`string-placeholder`: 92
`mustache`: 792,467
`string-template`: 971,783

I think only `mustache` and `strign-tempate` should be considered for the implementation, due to number of downloads.

**Comment by lcor-io** [comment]
By looking at the docs, I guess they are both fine and match our needs. `string-template` is not updated since 3 years tho

**Comment by lcor-io** [comment]
Since I think that `mustache` got slightly more functionnalities, I guess my preference goes to this one

**Comment by tanohzana** [comment]
That is true, but it means that it's been stable for 3 years 😛 
What I'll do is use : 

* `string-template` for the dumb component
* `mustache` for the container 😉 

Then we can discuss this on the PR 👌
