### ISSUE TITLE
Add flow as a parameter

### ISSUE THREAD

**Issue by tanohzana** [tanohzana/reacli#2]
**Is your feature request related to a problem? Please describe.**
Sometimes people use Flow combined with React. CLI should support it.

**Describe the solution you'd like**
A template using Flow should be implemented.
Whenever the user types `reacli component --flow <path>`, template that uses Flow should be used.

**Comment by gdarchen** [comment]
I propose to handle this issue by dynamically modifying the generated component as follows: 

- In the _container component_, we have to add the `// @flow` annotation as well as define the type of the state
- In the _dumb component_, we also have to add the `// @flow` annotation, and we have to define the props type and the default props values

What do you think? 😄

**Comment by tanohzana** [comment]
You're good to go. Hit me up if you need help

**Comment by tanohzana** [comment]
Part of issue #5
