### ISSUE TITLE
Update documentation with new features

### ISSUE THREAD

**Issue by tanohzana** [tanohzana/reacli#23]
**Is your feature request related to a problem? Please describe.**
New features were implemented and doc is not up to date anymore.

**Describe the solution you'd like**
README should be updated, and I think a plan to update documentation each week should be enforced.

**Comment by gdarchen** [comment]
It should also be great to update links in `CONTRIBUTING.md` since we changed the repository location (to make it belong to the "reacli" organization), even if links to the old repository automatically redirect to the new one.

**Comment by marielenna** [comment]
Hey, not sure if this is open for others to assist with, but I'd like to help.

**Comment by tanohzana** [comment]
Hey ! Of course you can help ! If you know JavaScript, I’d suggest you try issue #1 which is pretty easy and straightforward 😉 but if you want to do this one, feel free to contribute. However, make sure you know everything Reacli does now ! We are here to assist

**Comment by marielenna** [comment]
@tanohzana do you have a list of the new features that need to be added to the readme? If so, can you provide them?

**Comment by tanohzana** [comment]
@marieram basically:
* redux option `reacli component my-component --redux`
* flow option `reacli component my-component --flow`
* scss or css option `reacli component my-component --scss`

**Comment by tanohzana** [comment]
@marieram any updates ? :-)

**Comment by gdarchen** [comment]
Hey, @tanohzana @marieram, solving this issue could also be a great occasion to add some link in the `README.md` to the [CLI landing website (https://reacli.github.io)](https://reacli.github.io). 😊

**Comment by marielenna** [comment]
@tanohzana This is over my head. Someone else can take over. Thanks

**Comment by gdarchen** [comment]
Maybe we could just create a nearly empty `README.md` and just give a link to the landing page? Something like [`create-react-app`'s `README.md`](https://www.npmjs.com/package/create-react-app)?
