### ISSUE TITLE
Create a landing page thanks to Github Pages

### ISSUE THREAD

**Issue by gdarchen** [tanohzana/reacli#24]
**Is your feature request related to a problem? Please describe.**
Documentation are most of the time written in simple README file. It always looks the same and can be boring to read. Moreover, it might be hard to find the exact point we are searching in the documentation.

**Describe the solution you'd like**
Create a beautiful landing page could make the documentation more readable or more pleasant to be read. To create the landing page, we could use Github Pages and work on a `gh-pages` dedicated branch.

**Describe alternatives you've considered**
We could also just write the documentation in a simple ready and let the application not being easily distinguishable thanks its pretty documentation 😛

**Comment by tanohzana** [comment]
It would also be very interesting to create another repo, next to `cli`, to host the website as an open source project. That's what a thought we were going to do...
Also, I think this is a big issue that we should have discussed before trying to implement it.

That's what I was picturing as a landing page / repo aside from `cli`:
https://guides.github.com/features/pages/

**Comment by gdarchen** [comment]
You are right: I am working on it on the https://github.com/reacli/cli-docs repository.
You can find the generated Gtihub Pages here: https://reacli.github.io/cli-docs
