### ISSUE TITLE
Boilerplate for Hooks

### ISSUE THREAD

**Issue by alexandre-lelain** [tanohzana/reacli#26]
**Is your feature request related to a problem? Please describe.**
Hooks just got released with React 16.8.0! It would be great to add a hook boilerplate in the project, in addition to the traditional component class.

**Describe the solution you'd like**
Add `hook` option to the cli command so the users can create a hook OR a component:

```
reacli hook <path>
```

**Comment by alexandre-lelain** [comment]
Maybe we could add some warning system to notify the user that his/her project will need `React: ^16.8.0` for the hook to work.

**Comment by gdarchen** [comment]
Hi! 
That's a great idea. For sure, we will handle this issue in a future pull request.
Thanks a lot for your contribution! 😊

**Comment by tanohzana** [comment]
@alexandre-lelain any updates ? Think about creating a fork for your modifications 😉

**Comment by alexandre-lelain** [comment]
Will work on it soon
