### ISSUE TITLE
Enhance component's template to make it customizable

### ISSUE THREAD

**Issue by gdarchen** [tanohzana/reacli#5]
**Is your feature request related to a problem? Please describe.**
We could include into the generated files some optional tags that we could work with depending on the given parameters.

**Describe the solution you'd like**
We could imagine some keywords describing the places in the files where we would modify this or that thing.

For instance, for the `--flow` option, we could look up for the optional `[[flow-declaration]]` in the template to replace it with something like `// @flow`. The `[[flow-props-type]]` tag would be the key to find the place where we can write our flow-typed props...

**Comment by tanohzana** [comment]
Good idea ;-)
