### ISSUE TITLE
Propose a CI implementation and tool

### ISSUE THREAD

**Issue by tanohzana** [tanohzana/reacli#7]
**Is your feature request related to a problem? Please describe.**
CI is not implemented on this project. It should be.

**Describe the solution you'd like**
We are open to trying new tools. Travis ? CircleCI ? We need a proposal.

**Comment by lcor-io** [comment]
From what I read, it looks like Travis could be good because it doesn't need much configuration. Jenkins is also good, but we will need much more time to setup the pipellines, and we will  need dedicated server.
I don't have any experience with CircleCI
